/*
    module  : mktime.c
    version : 1.1
    date    : 03/21/24
*/
#ifndef MKTIME_C
#define MKTIME_C

#include "decode.h"

/**
Q0  OK  1720  mktime  :  DA  T  ->  I
Converts a list T representing local time into a time I.
T is in the format generated by localtime.
*/
void mktime_(pEnv env)
{
    Node node;
    struct tm t;

    PARM(1, HELP);
    node = vec_pop(env->stack);
    decode(node, &t);
    node.u.num = mktime(&t);
    node.op = INTEGER_;
    vec_push(env->stack, node);
}
#endif
